// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LocalyticsSampleApp {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UIButton __mt_button;
		
		private MonoTouch.UIKit.UIButton __mt_upload;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("button")]
		private MonoTouch.UIKit.UIButton button {
			get {
				this.__mt_button = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("button")));
				return this.__mt_button;
			}
			set {
				this.__mt_button = value;
				this.SetNativeField("button", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("upload")]
		private MonoTouch.UIKit.UIButton upload {
			get {
				this.__mt_upload = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("upload")));
				return this.__mt_upload;
			}
			set {
				this.__mt_upload = value;
				this.SetNativeField("upload", value);
			}
		}
	}
}
